name: game2048_pipeline

on:
  push:
    branches:
      - main

env:
  maven_packages_cache: ".m2/repository"
  MAVEN_OPTS: "-Dmaven.repo.local=./$maven_packages_cache"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: temurin

      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ${{ env.maven_packages_cache }}
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        run: mvn compile $MAVEN_OPTS

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}-${{ github.ref_slug }}-${{ github.sha }}
          path: target/*
      
  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: temurin

      - name: Restore Maven Packages from Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.maven_packages_cache }}
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Test
        run: mvn test $MAVEN_OPTS

      - name: Archive Test Reports and Coverage
        uses: actions/upload-artifact@v2
        with:
          path: |
            target/surefire-reports/*
            target/site/jacoco/*
