name: game2048_pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Maven
        run: |
          sudo apt-get install -y maven

      - name: Build
        run: mvn compile

      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}-$GITHUB_REF_SLUG-${{ github.sha }}
          path: target/*

      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Restore Maven Packages from Cache
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Install Maven
        run: |
          sudo apt-get install -y maven

      - name: Test
        run: mvn test

      - name: Archive Test Reports and Coverage
        uses: actions/upload-artifact@v2
        with:
          path: |
            target/surefire-reports/*
            target/site/jacoco/*

      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
